from django.db import models

# Create your models here.


# class Destination:
#     id:int
#     name:str
#     imag:str
#     desc:str
#     price:int
#     offer:bool

class Destination(models.Model):
    # no need for id it will be generated by postgres datbase
    name= models.CharField(max_length=100)
    imag= models.ImageField(upload_to='picture')
    desc=models.TextField()
    price=models.IntegerField()
    offer= models.BooleanField(default=False)
    